# Generated by Django 4.0.5 on 2022-10-21 05:53

from django.db import migrations, models
import src.common.models.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, help_text='Size of file in bytes', null=True, verbose_name='Size')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='Name')),
                ('extension', models.CharField(blank=True, default='', max_length=255, verbose_name='Extension')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content', models.FileField(upload_to=src.common.models.file.file_path_generator, verbose_name='File')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'file',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, help_text='Size of file in bytes', null=True, verbose_name='Size')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='Name')),
                ('extension', models.CharField(blank=True, default='', max_length=255, verbose_name='Extension')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content', models.ImageField(upload_to=src.common.models.file.file_path_generator, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'common_image',
                'ordering': ('-id',),
            },
        ),
    ]
